package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"go.yaml.in/yaml/v3"
)

// codegenSkill emits the auto-generated reference index that SKILL.md points
// agents at: a markdown table per section listing every operation, its class,
// reversibility, sync/async flag, identifier shape, and one-line summary.
//
// Per spec section 10, this is the *only* file under skills/ws1-uem/reference/
// that gets regenerated on each spec sync; the other concept and pattern
// files are hand-written.
func newCodegenSkillCmd() *cobra.Command {
	var indexPath, policyPath, outDir string
	cmd := &cobra.Command{
		Use:   "codegen-skill",
		Short: "Regenerate skills/ws1-uem/reference/operation-index.md",
		RunE: func(cmd *cobra.Command, args []string) error {
			ops, err := loadOpIndexJSONFull(indexPath)
			if err != nil {
				return err
			}
			policy, err := loadPolicyForSkill(policyPath)
			if err != nil {
				return err
			}
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return err
			}
			out := filepath.Join(outDir, "operation-index.md")
			if err := writeOperationIndex(out, ops, policy); err != nil {
				return err
			}
			fmt.Fprintf(os.Stderr, "codegen-skill: wrote %s (%d ops)\n", out, len(ops))
			return nil
		},
	}
	cmd.Flags().StringVar(&indexPath, "index", "internal/generated/ops_index.json", "ops index sidecar")
	cmd.Flags().StringVar(&policyPath, "policy", "operations.policy.yaml", "policy file")
	cmd.Flags().StringVar(&outDir, "out", "skills/ws1-uem/reference/", "output directory")
	return cmd
}

type fullOpIndex struct {
	Op             string         `json:"op"`
	Section        string         `json:"section"`
	Tag            string         `json:"tag"`
	Verb           string         `json:"verb"`
	HTTPMethod     string         `json:"http_method"`
	PathTemplate   string         `json:"path_template"`
	Summary        string         `json:"summary"`
	HasRequestBody bool           `json:"has_request_body"`
}

type policyEntry struct {
	Class      string `yaml:"class"`
	Reversible string `yaml:"reversible"`
	Sync       *bool  `yaml:"sync"`
	Identifier string `yaml:"identifier"`
}

func loadOpIndexJSONFull(path string) ([]fullOpIndex, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var raw []fullOpIndex
	if err := yaml.Unmarshal(b, &raw); err != nil {
		// JSON is a YAML subset; this works fine for both.
		return nil, fmt.Errorf("parse ops index: %w", err)
	}
	return raw, nil
}

func loadPolicyForSkill(path string) (map[string]policyEntry, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc map[string]any
	if err := yaml.Unmarshal(b, &doc); err != nil {
		return nil, err
	}
	out := map[string]policyEntry{}
	for k, v := range doc {
		if k == "version" {
			continue
		}
		bb, _ := yaml.Marshal(v)
		var entry policyEntry
		if err := yaml.Unmarshal(bb, &entry); err == nil {
			out[k] = entry
		}
	}
	return out, nil
}

func writeOperationIndex(path string, ops []fullOpIndex, policy map[string]policyEntry) error {
	// Group by section.
	bySection := map[string][]fullOpIndex{}
	for _, o := range ops {
		bySection[o.Section] = append(bySection[o.Section], o)
	}
	sections := make([]string, 0, len(bySection))
	for s := range bySection {
		sections = append(sections, s)
	}
	sort.Strings(sections)

	var b strings.Builder
	fmt.Fprintf(&b, "# Operation index\n\n")
	fmt.Fprintf(&b, "_Auto-generated by `ws1-build codegen-skill` at %s. Do not edit by hand; rerun the maintainer pipeline after spec changes._\n\n",
		time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "Total operations: **%d** across **%d** section(s).\n\n", len(ops), len(sections))
	fmt.Fprintf(&b, "Columns:\n- **Op identifier**: canonical name to pass to `ws1 ops describe`.\n- **Class**: `read` / `write` / `destructive`. Destructive ops always require browser approval.\n- **Reversible**: `full` / `partial` / `none` / `unknown`. Affects how confidently an agent should propose the op.\n- **Sync**: `sync` returns a result inline; `async` returns a `job_id` to poll.\n- **Identifier**: argv shape needed to target the op (`device_id`, `device_id_array`, etc.).\n- **Summary**: one-line description from the spec.\n\n")

	for _, section := range sections {
		fmt.Fprintf(&b, "## %s\n\n", section)
		fmt.Fprintf(&b, "| Op identifier | Class | Reversible | Sync | Identifier | Summary |\n")
		fmt.Fprintf(&b, "|---|---|---|---|---|---|\n")
		section := bySection[section]
		sort.Slice(section, func(i, j int) bool {
			if section[i].Tag != section[j].Tag {
				return section[i].Tag < section[j].Tag
			}
			return section[i].Verb < section[j].Verb
		})
		for _, o := range section {
			pol := policy[o.Op]
			class := pol.Class
			if class == "" {
				class = "_unclassified_"
			}
			rev := pol.Reversible
			if rev == "" {
				rev = "—"
			}
			sync := "—"
			if pol.Sync != nil {
				if *pol.Sync {
					sync = "sync"
				} else {
					sync = "async"
				}
			}
			ident := pol.Identifier
			if ident == "" {
				ident = "—"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s |\n", o.Op, class, rev, sync, ident, escapePipe(o.Summary))
		}
		fmt.Fprintln(&b)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func escapePipe(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
