package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

// codegenCLI emits a single Go source file under internal/generated/ that
// contains the canonical metadata for every operation across every spec.
//
// We avoid per-section generated files for v0 because the typed-binding
// approach (one struct per op) explodes to thousands of types across all
// WS1 sections. Instead we emit a single Ops map keyed by canonical
// identifier; the runtime API client uses the metadata to bind argv to
// HTTP requests generically.
//
// A companion ops_index.json is also written so codegen-skill and
// classify-check can consume the same data without depending on the Go
// generator.
func newCodegenCLICmd() *cobra.Command {
	var specsDir, outDir string
	cmd := &cobra.Command{
		Use:   "codegen-cli",
		Short: "Generate Go bindings from spec/* into internal/generated/",
		RunE: func(cmd *cobra.Command, args []string) error {
			specs, err := loadSpecs(specsDir)
			if err != nil {
				return err
			}
			var allOps []opRow
			var allWarnings []string
			for _, s := range specs {
				rows, warnings, err := extractOps(s)
				if err != nil {
					return err
				}
				allOps = append(allOps, rows...)
				allWarnings = append(allWarnings, warnings...)
			}
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return err
			}
			if err := emitOpsIndexGo(filepath.Join(outDir, "ops_index.go"), allOps); err != nil {
				return err
			}
			if err := emitOpsIndexJSON(filepath.Join(outDir, "ops_index.json"), allOps); err != nil {
				return err
			}
			fmt.Fprintf(os.Stderr, "codegen-cli: wrote %d operations across %d sections to %s\n", len(allOps), len(specs), outDir)
			for _, w := range allWarnings {
				fmt.Fprintln(os.Stderr, "  warning:", w)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&specsDir, "specs", "spec/", "directory containing OpenAPI 3.0.1 spec files")
	cmd.Flags().StringVar(&outDir, "out", "internal/generated/", "output directory for generated Go code")
	return cmd
}

const opsIndexTemplate = `// Code generated by ws1-build. DO NOT EDIT.

// Package generated contains the compiled-in operation index for the ws1
// CLI. It's the authoritative mapping from canonical operation identifiers
// (e.g. "mdmv4.devices.search") to HTTP method, path template, parameter
// metadata, and human-readable description.
//
// Regenerate via: make sync-specs (or ws1-build codegen-cli).
package generated

// ParamMeta describes one operation parameter.
type ParamMeta struct {
	Name        string
	In          string // path | query | header
	Required    bool
	Type        string
	Description string
}

// OpMeta is the compiled record for a single operation.
type OpMeta struct {
	Op             string
	Section        string
	Tag            string
	Verb           string
	HTTPMethod     string
	PathTemplate   string
	BasePath       string
	OperationID    string
	Summary        string
	Description    string
	Parameters     []ParamMeta
	HasRequestBody bool
}

// Ops is the compiled-in catalog. Key is the canonical operation identifier.
var Ops = map[string]OpMeta{
{{range .}}	{{printf "%q" .Op}}: {
		Op:             {{printf "%q" .Op}},
		Section:        {{printf "%q" .Section}},
		Tag:            {{printf "%q" .Tag}},
		Verb:           {{printf "%q" .Verb}},
		HTTPMethod:     {{printf "%q" .HTTPMethod}},
		PathTemplate:   {{printf "%q" .PathTemplate}},
		BasePath:       {{printf "%q" .BasePath}},
		OperationID:    {{printf "%q" .OperationID}},
		Summary:        {{printf "%q" .Summary}},
		Description:    {{printf "%q" .Description}},
		HasRequestBody: {{.HasRequestBody}},
		Parameters: []ParamMeta{
{{range .Parameters}}			{Name: {{printf "%q" .Name}}, In: {{printf "%q" .In}}, Required: {{.Required}}, Type: {{printf "%q" .Schema.Type}}, Description: {{printf "%q" .Description}}},
{{end}}		},
	},
{{end}}}

// Sections returns the unique set of section slugs present in Ops, sorted.
func Sections() []string {
	seen := map[string]struct{}{}
	for _, m := range Ops {
		seen[m.Section] = struct{}{}
	}
	out := make([]string, 0, len(seen))
	for s := range seen {
		out = append(out, s)
	}
	// stable order: simple insertion sort is fine for ~10 sections.
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j-1] > out[j]; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}
`

func emitOpsIndexGo(path string, ops []opRow) error {
	tpl, err := template.New("ops").Parse(opsIndexTemplate)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, ops); err != nil {
		return err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Fall back to unformatted output so the maintainer can debug.
		// gofmt failure here usually means a template bug.
		return fmt.Errorf("gofmt generated source: %w\n--- raw output ---\n%s", err, buf.String())
	}
	return os.WriteFile(path, formatted, 0o644)
}

// emitOpsIndexJSON writes the same metadata as a JSON sidecar so other
// pipeline stages (codegen-skill, classify-check) can read it without
// depending on a Go build of internal/generated.
func emitOpsIndexJSON(path string, ops []opRow) error {
	type sidecarParam struct {
		Name        string `json:"name"`
		In          string `json:"in"`
		Required    bool   `json:"required"`
		Type        string `json:"type"`
		Description string `json:"description,omitempty"`
	}
	type sidecarOp struct {
		Op             string         `json:"op"`
		Section        string         `json:"section"`
		Tag            string         `json:"tag"`
		Verb           string         `json:"verb"`
		HTTPMethod     string         `json:"http_method"`
		PathTemplate   string         `json:"path_template"`
		BasePath       string         `json:"base_path"`
		OperationID    string         `json:"operation_id"`
		Summary        string         `json:"summary,omitempty"`
		Description    string         `json:"description,omitempty"`
		HasRequestBody bool           `json:"has_request_body"`
		Parameters     []sidecarParam `json:"parameters"`
	}
	out := make([]sidecarOp, 0, len(ops))
	for _, r := range ops {
		so := sidecarOp{
			Op: r.Op, Section: r.Section, Tag: r.Tag, Verb: r.Verb,
			HTTPMethod: r.HTTPMethod, PathTemplate: r.PathTemplate, BasePath: r.BasePath,
			OperationID: r.OperationID, Summary: r.Summary, Description: r.Description,
			HasRequestBody: r.HasRequestBody,
		}
		for _, p := range r.Parameters {
			so.Parameters = append(so.Parameters, sidecarParam{
				Name: p.Name, In: p.In, Required: p.Required,
				Type: p.Schema.Type, Description: p.Description,
			})
		}
		out = append(out, so)
	}
	b, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, append(b, '\n'), 0o644); err != nil {
		return err
	}
	return nil
}

// stringSliceContains is a tiny helper to keep template logic readable.
func stringSliceContains(s []string, want string) bool {
	for _, v := range s {
		if v == want {
			return true
		}
	}
	return false
}

// (kept exported-style local for symmetry with future helpers)
var _ = strings.TrimSpace
